INSERT INTO category (name)
VALUES
    ('ALIMENTACAO'),
    ('PETSHOP'),
    ('PRODUTOS_ARTESANAIS'),
    ('PAPELARIA'),
    ('FLORES_E_PLANTAS'),
    ('BELEZA_E_ESTETICA'),
    ('MANUTENCAO_AUTOMOVEIS'),
    ('LIMPEZA_AUTOMOVEIS'),
    ('LIVRARIA'),
    ('PERFUMARIA'),
    ('VESTUARIO_CALCADOS'),
    ('INFORMATICA_ELETRONICOS')
    ON CONFLICT (name) DO NOTHING;